name: Check PR

on:
  pull_request:
    branches:
      - master

jobs:
  check-pr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: ./buildandtest

