name: Check PR

on:
  pull_request:
    branches:
      - master

jobs:
  check-pr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - name: Test
        run: ctest --test-dir ${{github.workspace}} --output-on-failure
